### ISSUE TITLE
Decision on repository ID

### ISSUE THREAD

**Issue by hohwille** [devonfw/maven-parent#14]
As a devonfw-deployer, I want to have stable deployment logic so that I do not have to update my settings and hunt down errors when deployment to OSSRH fails.
With commit https://github.com/devonfw/maven-parent/commit/faf9389483fe1025655e3c414340dad1744facb8 the repository ID has been changed.
With this issue I would like to clarify the rationale behind this.
At least the cons against this change are:
* existing `settings.xml` files of users and automated pipelines already contain the repository ID `repository`. With that change those would break.
* during the update of a new maven-parent accross devonfw repositories some deployments would require the existing repository ID `repository` while others have already been updated and require the new one `ossrh`. As a result we would need to put both IDs with according credentials into all `settings.xml`

Just to outline the impact of your change:
* https://github.com/devonfw/devon4j/blob/79864633341ef743b3e56e45e9d43e19e168f655/.mvn/settings.xml#L5
* https://github.com/devonfw/ide/blob/de8e9b4c8ed7e78826d1faa982877bae9e1057b3/.mvn/settings.xml#L6
* https://github.com/devonfw/docgen/blob/119cf61eacbb9441bc324cb47ad3631a3b1f9487/.mvn/settings.xml#L10
* https://github.com/devonfw/sonar-devon4j-plugin/blob/5413bf97221e752c648953ea3cd052c9ec39294d/.mvn/settings.xml#L6
* https://github.com/devonfw/cobigen/blob/master/.mvn/settings.xml
* ...  and many `settings.xml` files on local computers (at least for me)

So my suggestion would rather be to revert this change and consider aligning the repos of devonfw that do not yet follow the repository ID and parent POM strategy that once has been discussed and agreed for devonfw.

**Comment by maybeec** [comment]
The rational was basically to standardize the same repository on a common ID. So far, there were `repository` as well as `ossrh` IDs within the pom. I am totally fine to standardize on either `ossrh` or `repository`.

Occurrences:

* https://github.com/devonfw/maven-parent/blob/master/pom.xml#L549
* https://github.com/devonfw/maven-parent/blob/master/pom.xml#L577
* https://github.com/devonfw/maven-parent/blob/master/pom.xml#L582

**Comment by hohwille** [comment]
IMHO we have used `repository` what is also more generic and have used it in a wider range than just the given links.
So more or less we have meanwhile decided to stick with `repository` and have to change other places where we do not follow this "standard".
